#+TITLE: My Private configs

* Accounts
** Set up User
#+BEGIN_SRC elisp
(setq user-full-name "Prasanth Krishnan"
      user-mail-address "knp281192@gmail.com")
#+END_SRC
* Projectile
Set the projects folder
#+BEGIN_SRC elisp
(setq projectile-project-search-path '("~/workspace/"))
#+END_SRC
* Editor
** Theme
There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the `load-theme' function. This is the default:
#+BEGIN_SRC elisp
(setq doom-theme 'doom-one)
#+END_SRC
** Line Numbers
#+BEGIN_SRC elisp
(setq display-line-numbers-type 'relative)
#+END_SRC
* Org
** Org directory
#+BEGIN_SRC elisp
(setq org-directory "~/org/")
#+END_SRC
* Macros
Here are some additional functions/macros that could help you configure Doom:

- `load!' for loading external *.el files relative to this one
- `use-package' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
  this file. Emacs searches the `load-path' when you load packages with
  `require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c g k').
This will open documentation for it, including demos of how they are used.

You can also try 'gd' (or 'C-c g d') to jump to their definition and see how
they are implemented.
* Window-select
** Increase the ace window leading char font size
#+BEGIN_SRC elisp
(custom-set-faces!
  '(aw-leading-char-face
    :foreground "white" :background "red"
    :weight bold :height 2.5 :box (:line-width 10 :color "red")))
#+END_SRC
* Avy
Expand avy search to all windows
#+begin_src elisp
(setq avy-all-windows t)
#+end_src
